//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntodeVenta_Cliente.cons {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cons.PaymentServiceSoap")]
    public interface PaymentServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsulaJson del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaBoletoRequest", ReplyAction="*")]
        PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse consultaBoletoRequest(PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/consultaBoletoRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse> consultaBoletoRequestAsync(PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsulaJson del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/revBoletoPagadoRequest", ReplyAction="*")]
        PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse revBoletoPagadoRequest(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/revBoletoPagadoRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse> revBoletoPagadoRequestAsync(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ConsulaJson del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/notiBoletoPagadoRequest", ReplyAction="*")]
        PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse notiBoletoPagadoRequest(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/notiBoletoPagadoRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse> notiBoletoPagadoRequestAsync(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaBoletoRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaBoletoRequest", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.consultaBoletoRequestRequestBody Body;
        
        public consultaBoletoRequestRequest() {
        }
        
        public consultaBoletoRequestRequest(PuntodeVenta_Cliente.cons.consultaBoletoRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaBoletoRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsulaJson;
        
        public consultaBoletoRequestRequestBody() {
        }
        
        public consultaBoletoRequestRequestBody(string ConsulaJson) {
            this.ConsulaJson = ConsulaJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaBoletoRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaBoletoRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.consultaBoletoRequestResponseBody Body;
        
        public consultaBoletoRequestResponse() {
        }
        
        public consultaBoletoRequestResponse(PuntodeVenta_Cliente.cons.consultaBoletoRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class consultaBoletoRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string consultaBoletoRequestResult;
        
        public consultaBoletoRequestResponseBody() {
        }
        
        public consultaBoletoRequestResponseBody(string consultaBoletoRequestResult) {
            this.consultaBoletoRequestResult = consultaBoletoRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class revBoletoPagadoRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="revBoletoPagadoRequest", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequestBody Body;
        
        public revBoletoPagadoRequestRequest() {
        }
        
        public revBoletoPagadoRequestRequest(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class revBoletoPagadoRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsulaJson;
        
        public revBoletoPagadoRequestRequestBody() {
        }
        
        public revBoletoPagadoRequestRequestBody(string ConsulaJson) {
            this.ConsulaJson = ConsulaJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class revBoletoPagadoRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="revBoletoPagadoRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponseBody Body;
        
        public revBoletoPagadoRequestResponse() {
        }
        
        public revBoletoPagadoRequestResponse(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class revBoletoPagadoRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string revBoletoPagadoRequestResult;
        
        public revBoletoPagadoRequestResponseBody() {
        }
        
        public revBoletoPagadoRequestResponseBody(string revBoletoPagadoRequestResult) {
            this.revBoletoPagadoRequestResult = revBoletoPagadoRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notiBoletoPagadoRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="notiBoletoPagadoRequest", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequestBody Body;
        
        public notiBoletoPagadoRequestRequest() {
        }
        
        public notiBoletoPagadoRequestRequest(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class notiBoletoPagadoRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsulaJson;
        
        public notiBoletoPagadoRequestRequestBody() {
        }
        
        public notiBoletoPagadoRequestRequestBody(string ConsulaJson) {
            this.ConsulaJson = ConsulaJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notiBoletoPagadoRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="notiBoletoPagadoRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponseBody Body;
        
        public notiBoletoPagadoRequestResponse() {
        }
        
        public notiBoletoPagadoRequestResponse(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class notiBoletoPagadoRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string notiBoletoPagadoRequestResult;
        
        public notiBoletoPagadoRequestResponseBody() {
        }
        
        public notiBoletoPagadoRequestResponseBody(string notiBoletoPagadoRequestResult) {
            this.notiBoletoPagadoRequestResult = notiBoletoPagadoRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentServiceSoapChannel : PuntodeVenta_Cliente.cons.PaymentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceSoapClient : System.ServiceModel.ClientBase<PuntodeVenta_Cliente.cons.PaymentServiceSoap>, PuntodeVenta_Cliente.cons.PaymentServiceSoap {
        
        public PaymentServiceSoapClient() {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse PuntodeVenta_Cliente.cons.PaymentServiceSoap.consultaBoletoRequest(PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest request) {
            return base.Channel.consultaBoletoRequest(request);
        }
        
        public string consultaBoletoRequest(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest inValue = new PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.consultaBoletoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse retVal = ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).consultaBoletoRequest(inValue);
            return retVal.Body.consultaBoletoRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse> PuntodeVenta_Cliente.cons.PaymentServiceSoap.consultaBoletoRequestAsync(PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest request) {
            return base.Channel.consultaBoletoRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.consultaBoletoRequestResponse> consultaBoletoRequestAsync(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest inValue = new PuntodeVenta_Cliente.cons.consultaBoletoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.consultaBoletoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            return ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).consultaBoletoRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse PuntodeVenta_Cliente.cons.PaymentServiceSoap.revBoletoPagadoRequest(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest request) {
            return base.Channel.revBoletoPagadoRequest(request);
        }
        
        public string revBoletoPagadoRequest(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest inValue = new PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse retVal = ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).revBoletoPagadoRequest(inValue);
            return retVal.Body.revBoletoPagadoRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse> PuntodeVenta_Cliente.cons.PaymentServiceSoap.revBoletoPagadoRequestAsync(PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest request) {
            return base.Channel.revBoletoPagadoRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.revBoletoPagadoRequestResponse> revBoletoPagadoRequestAsync(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest inValue = new PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.revBoletoPagadoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            return ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).revBoletoPagadoRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse PuntodeVenta_Cliente.cons.PaymentServiceSoap.notiBoletoPagadoRequest(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest request) {
            return base.Channel.notiBoletoPagadoRequest(request);
        }
        
        public string notiBoletoPagadoRequest(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest inValue = new PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse retVal = ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).notiBoletoPagadoRequest(inValue);
            return retVal.Body.notiBoletoPagadoRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse> PuntodeVenta_Cliente.cons.PaymentServiceSoap.notiBoletoPagadoRequestAsync(PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest request) {
            return base.Channel.notiBoletoPagadoRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestResponse> notiBoletoPagadoRequestAsync(string ConsulaJson) {
            PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest inValue = new PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequest();
            inValue.Body = new PuntodeVenta_Cliente.cons.notiBoletoPagadoRequestRequestBody();
            inValue.Body.ConsulaJson = ConsulaJson;
            return ((PuntodeVenta_Cliente.cons.PaymentServiceSoap)(this)).notiBoletoPagadoRequestAsync(inValue);
        }
    }
}
